### ISSUE TITLE
Current limitation of nomopyomo

### ISSUE THREAD

**Issue by camiloromers** [nworbmot/nomopyomo#2]
This is not actually a `bug`. It is jus a question to understand the idea behind nomopyomo.

What are the current limitation of nomopyomo if each time when I run it I receive the following message: 

> WARNING:nomopyomo:Committable generators are currently not supported. 

Does the optimizer still consider constrains like ramps, start up/down cost and so on, or just optimize around the marginal cost?

Thanks for your help.

**Comment by fneum** [comment]
`nomopyomo` was recently included in the pypsa repository: https://github.com/PyPSA/PyPSA/pull/99

Here's what it says about limitations of the unit commitment

```
        logger.warn("Unit commitment is not yet completely implemented for "
        "optimising without pyomo. Thus minimum up time, minimum down time, "
        "start up costs, shut down costs will be ignored.")
```

https://github.com/PyPSA/PyPSA/blob/257495e8f3a24d258efd9439d489808293170265/pypsa/linopf.py#L878-L881

**Comment by fneum** [comment]
If you have any further questions, please open an issue in the PyPSA repository or write to the mailing list for usage questions.
