### ISSUE TITLE
State of charge bug

### ISSUE THREAD

**Issue by OriolRaventos** [nworbmot/nomopyomo#3]
I calculated the lopf of a small example with 2 nodes and 2 snapshots (attached) and got a different optimal solution. With
```
network.lopf(solver_name="cbc",formulation="angles")
```
I get 879719.89 and with
```
nomopyomo.network_lopf(network, solver_name="cbc")
```
I get 904301.23. The same is true solving with gurobi. The problem seems to be the computation of the state of charge (in this case of cyclic and non extendable storage units). If I add the line
```
network.mremove("StorageUnit",network.storage_units.index)
```
the optimal solution is the same for both methods (904301.23). 

Attachment:
[nomopyomo_bug.zip](https://github.com/PyPSA/nomopyomo/files/5590583/nomopyomo_bug.zip)

**Comment by nworbmot** [comment]
`nomopyomo` has already been integrated into PyPSA and completely rewritten by @FabianHofmann, so I'd suggest to check whether this bug still holds in the latest version of PyPSA when you do:

`network.lopf(solver_name="cbc",formulation="angles",pyomo=False)`

The term `pyomo=False` activates the succesor to `nomopyomo`.

Thanks!

**Comment by OriolRaventos** [comment]
Yes, using ```pyomo=False``` both objective values coincide. Sorry that I got confused about the current version of the lopf without pyomo. Thank you for your fast response.

**Comment by nworbmot** [comment]
No worries, thanks for doing the checks, it's important to double-check the behaviour and be on the lookout for bugs!

**Comment by nworbmot** [comment]
I'll also put a warning on the repository that it's no longer under development.
